spring.application.name=gateway-service-api
server.port=8082

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/


#Keycloak config
spring.security.oauth2.resourceserver.jwt.token-uri=http://localhost:8080/realms/cpd/protocol/openid-connect/token
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/cpd
public.key.string=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArt+KvGefjuGia3zrnT5bnRKl1HUtvtcbqBS/0bzuI3UmsKxi/rTpPZuasl41+sEiyVIxVVkNc6nr4PGGF4tYTx0wsMQ3JRG6XRNOAmQ7JFD4K7mrID1YBRAniPy227ItlwDfhoP/Coto0N7b+3J/FgOtbaCA88QSRqF6DN+8pj3JL+2U001rjoyYjVJhMY7msKQ+/2Tv02w2N7jqRv613Wand3KUalUiWF+KVqTwVnYBCzNBvEZXJ689UeFbFH7KE5oXas/RiVxMvB0DO4GPh++j0PDBozq00mgRQw6rzmt6E9NSkpO674WwX/QxR4hEi0zinEJEbMxBPXJQvHtFlQIDAQAB

keycloak.config.realm=cpd
keycloak.config.server-url=http://localhost:8080/
keycloak.config.client-id=cpd-client
keycloak.config.grant-type=password
keycloak.config.name=suwanthadarshana@gmail.com
keycloak.config.secret=wGn1tpxcq0nhxsglbcgfuS3YAzr5UhJV
keycloak.config.password=1234